/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingApprovalRouteImport } from './routes/waiting-approval'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppResearcherRouteImport } from './routes/_app.researcher'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProgramsRouteImport } from './routes/_app.programs'
import { Route as AppOrganizationsRouteImport } from './routes/_app.organizations'
import { Route as AppManagerRouteImport } from './routes/_app.manager'
import { Route as AppEmployeeRouteImport } from './routes/_app.employee'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppReportsNewRouteImport } from './routes/_app.reports.new'
import { Route as AppReportsReportIdRouteImport } from './routes/_app.reports.$reportId'

const WaitingApprovalRoute = WaitingApprovalRouteImport.update({
  id: '/waiting-approval',
  path: '/waiting-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppResearcherRoute = AppResearcherRouteImport.update({
  id: '/researcher',
  path: '/researcher',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsRoute = AppProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeRoute = AppEmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsNewRoute = AppReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AppReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/admin': typeof AppAdminRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/employee': typeof AppEmployeeRoute
  '/manager': typeof AppManagerRoute
  '/organizations': typeof AppOrganizationsRoute
  '/programs': typeof AppProgramsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/researcher': typeof AppResearcherRoute
  '/users': typeof AppUsersRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/reports/new': typeof AppReportsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/admin': typeof AppAdminRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/employee': typeof AppEmployeeRoute
  '/manager': typeof AppManagerRoute
  '/organizations': typeof AppOrganizationsRoute
  '/programs': typeof AppProgramsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/researcher': typeof AppResearcherRoute
  '/users': typeof AppUsersRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/reports/new': typeof AppReportsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/employee': typeof AppEmployeeRoute
  '/_app/manager': typeof AppManagerRoute
  '/_app/organizations': typeof AppOrganizationsRoute
  '/_app/programs': typeof AppProgramsRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/researcher': typeof AppResearcherRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/reports/$reportId': typeof AppReportsReportIdRoute
  '/_app/reports/new': typeof AppReportsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/landing'
    | '/login'
    | '/unauthorized'
    | '/waiting-approval'
    | '/admin'
    | '/audit-logs'
    | '/employee'
    | '/manager'
    | '/organizations'
    | '/programs'
    | '/reports'
    | '/researcher'
    | '/users'
    | '/reports/$reportId'
    | '/reports/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/landing'
    | '/login'
    | '/unauthorized'
    | '/waiting-approval'
    | '/admin'
    | '/audit-logs'
    | '/employee'
    | '/manager'
    | '/organizations'
    | '/programs'
    | '/reports'
    | '/researcher'
    | '/users'
    | '/reports/$reportId'
    | '/reports/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin-login'
    | '/landing'
    | '/login'
    | '/unauthorized'
    | '/waiting-approval'
    | '/_app/admin'
    | '/_app/audit-logs'
    | '/_app/employee'
    | '/_app/manager'
    | '/_app/organizations'
    | '/_app/programs'
    | '/_app/reports'
    | '/_app/researcher'
    | '/_app/users'
    | '/_app/reports/$reportId'
    | '/_app/reports/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  WaitingApprovalRoute: typeof WaitingApprovalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-approval': {
      id: '/waiting-approval'
      path: '/waiting-approval'
      fullPath: '/waiting-approval'
      preLoaderRoute: typeof WaitingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/researcher': {
      id: '/_app/researcher'
      path: '/researcher'
      fullPath: '/researcher'
      preLoaderRoute: typeof AppResearcherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs': {
      id: '/_app/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AppProgramsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations': {
      id: '/_app/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employee': {
      id: '/_app/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof AppEmployeeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/new': {
      id: '/_app/reports/new'
      path: '/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AppReportsNewRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/$reportId': {
      id: '/_app/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppReportsRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
  AppReportsNewRoute: typeof AppReportsNewRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsReportIdRoute: AppReportsReportIdRoute,
  AppReportsNewRoute: AppReportsNewRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppEmployeeRoute: typeof AppEmployeeRoute
  AppManagerRoute: typeof AppManagerRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppProgramsRoute: typeof AppProgramsRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppResearcherRoute: typeof AppResearcherRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppEmployeeRoute: AppEmployeeRoute,
  AppManagerRoute: AppManagerRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppProgramsRoute: AppProgramsRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppResearcherRoute: AppResearcherRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WaitingApprovalRoute: WaitingApprovalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
